#include "kpm_embed.h"
#include "analyze/base_func.h"
#include "3rdparty/aarch64_asm_helper.h"

using namespace asmjit;
using namespace asmjit::a64;
using namespace asmjit::a64::Predicate;

/*
 * Generate the '@' command prefix check to be inserted into the do_execve hook.
 *
 * This is a small shellcode snippet that:
 *   1. Checks if the first character of the execve filename is '@'
 *   2. If yes, branches to the KPM command handler
 *   3. If no, falls through to the original execve path
 *
 * The generated bytes are meant to be inserted at the end of the do_execve
 * hook's "key mismatch" path, just before the branch back to original do_execve.
 *
 * Parameters:
 *   filename_reg      — which register holds the filename pointer (x0 or x1)
 *   insert_addr       — the kernel address where this snippet will be placed
 *   kpm_handler_addr  — the kernel address of the KPM command handler
 *
 * Returns the patch bytes for this snippet.
 */
std::vector<patch_bytes_data> kpm_generate_execve_dispatch(
    int filename_reg,
    size_t insert_addr,
    size_t kpm_handler_addr)
{
    std::vector<patch_bytes_data> result;

    aarch64_asm_ctx asm_ctx = init_aarch64_asm();
    auto a = asm_ctx.assembler();
    Label fallthrough = a->newLabel();

    /* Load first byte of filename */
    a->ldrb(w15, ptr(a64::x(filename_reg)));

    /* Compare with '@' */
    a->cmp(w15, Imm('@'));

    /* If not '@', fall through to original execve */
    a->b(CondCode::kNE, fallthrough);

    /* It's a KPM command — branch to the handler */
    int64_t b_offset = (int64_t)kpm_handler_addr - (int64_t)(insert_addr + a->offset());
    aarch64_asm_b(a, (int32_t)b_offset);

    a->bind(fallthrough);
    /* nop placeholder — caller will append their original jump-back here */
    a->nop();

    std::vector<uint8_t> bytes = aarch64_asm_to_bytes(a);
    if (bytes.empty()) return result;

    std::string str_bytes = bytes2hex(bytes.data(), bytes.size());
    result.push_back({ str_bytes, insert_addr });

    return result;
}

/*
 * Generate the KPM command handler wrapper shellcode.
 *
 * This is a trampoline placed at the KPM handler address that:
 *   1. Saves the execve context (filename reg, return address)
 *   2. Sets up the call to kpm_main():
 *      x0 = pointer to KpmSystemTable
 *      x1 = command type (0=LOAD, 1=UNLOAD, 2=LIST)
 *      x2 = the filename string (from execve)
 *      x3 = 0
 *   3. Calls kpm_main entry point
 *   4. Restores context and returns
 *
 * The kpm_main C function parses the command string and handles everything.
 *
 * Parameters:
 *   handler_addr        — kernel address where this handler is placed
 *   system_table_addr   — kernel address of the KpmSystemTable
 *   loader_entry_addr   — kernel address of kpm_main (start of loader binary)
 */
std::vector<patch_bytes_data> kpm_generate_handler_wrapper(
    int filename_reg,
    size_t handler_addr,
    size_t system_table_addr,
    size_t loader_entry_addr)
{
    std::vector<patch_bytes_data> result;

    aarch64_asm_ctx asm_ctx = init_aarch64_asm();
    auto a = asm_ctx.assembler();

    /* Save return context */
    a->stp(x29, x30, ptr(sp).pre(-16));
    a->mov(x29, sp);

    /* Save the filename pointer and any other regs we need */
    a->stp(x0, x1, ptr(sp).pre(-16));
    a->stp(x2, x3, ptr(sp).pre(-16));
    a->stp(x4, x5, ptr(sp).pre(-16));

    /* x0 = &system_table (via ADRP + ADD) */
    {
        uint64_t cur_addr = handler_addr + a->offset();
        aarch64_asm_adrp_add_x(a, x0, cur_addr, system_table_addr);
    }

    /* x1 = 0 (command type — let C code parse from filename) */
    a->mov(x1, xzr);

    /* x2 = filename pointer (restore from saved regs) */
    a->mov(x2, a64::x(filename_reg));

    /* x3 = 0 */
    a->mov(x3, xzr);

    /* Call kpm_main */
    {
        size_t bl_addr = handler_addr + a->offset();
        int64_t diff = (int64_t)loader_entry_addr - (int64_t)bl_addr;
        if (!aarch64_asm_bl_raw(a, (int32_t)diff)) {
            std::cout << "[ERROR] KPM handler BL out of range" << std::endl;
            return result;
        }
    }

    /* Restore saved regs */
    a->ldp(x4, x5, ptr(sp).post(16));
    a->ldp(x2, x3, ptr(sp).post(16));
    a->ldp(x0, x1, ptr(sp).post(16));

    /* Restore frame and return */
    a->ldp(x29, x30, ptr(sp).post(16));
    a->ret(x30);

    std::vector<uint8_t> bytes = aarch64_asm_to_bytes(a);
    if (bytes.empty()) return result;

    std::string str_bytes = bytes2hex(bytes.data(), bytes.size());
    result.push_back({ str_bytes, handler_addr });

    return result;
}
