#include "kpm_embed.h"
#include "analyze/base_func.h"
#include "patch_base.h"
#include "3rdparty/aarch64_asm_helper.h"

/* Generated by kpm/Makefile */
#include "kpm/kpm_loader_data.h"
#include "kpm/kpm_loader_layout.h"

using namespace asmjit;
using namespace asmjit::a64;

/* Forward declaration from kpm_command.cpp */
extern std::vector<patch_bytes_data> kpm_generate_handler_wrapper(
    int filename_reg, bool filename_is_direct, size_t handler_addr,
    size_t system_table_addr, size_t loader_entry_addr);

/* Total size needed in kernel memory:
 *   handler_wrapper (~256 bytes)
 * + KPM loader binary (KPM_LOADER_BIN_SIZE)
 * + KpmSystemTable (sizeof(kpm_system_table) + alignment)
 */
#define KPM_WRAPPER_ESTIMATE  512
/*
 * kpm_loader.elf is linked as a flat image at VMA 0 and contains AArch64 ADRP
 * references between .text/.rodata/.got.  ADRP is page-relative, so relocating
 * the already-linked flat image to an arbitrary 8-byte aligned address is not
 * safe: if the runtime base has a non-zero 4 KiB page offset, page(symbol) -
 * page(PC) can differ from the link-time value and rodata/GOT accesses become
 * shifted/corrupted.
 *
 * Keep the embedded loader image 4 KiB aligned in the kernel code cave.  The
 * extra 0x1000 slack covers the worst-case padding from the handler wrapper to
 * the next page boundary.
 */
#define KPM_LOADER_ALIGN      0x1000ULL
#define KPM_TOTAL_NEEDED  (KPM_WRAPPER_ESTIMATE + (KPM_LOADER_ALIGN - 1) + KPM_LOADER_BIN_SIZE + sizeof(kpm_system_table) + 64)

size_t kpm_required_space() {
    return KPM_TOTAL_NEEDED;
}

static void embed_system_table_bytes(const KpmEmbedConfig& config,
                                     std::vector<patch_bytes_data>& out,
                                     size_t table_addr,
                                     size_t loader_bin_addr) {
    kpm_system_table sys;
    memset(&sys, 0, sizeof(sys));

    auto kva = [&](uint64_t addr) -> uint64_t {
        if (!addr) return 0;
        if (config.kernel_va_base && addr < config.kernel_file_buf->size()) {
            return config.kernel_va_base + addr;
        }
        return addr;
    };

    sys.kallsyms_lookup_name = (void* (*)(const char*))(unsigned long)kva(config.kallsyms_lookup_name_addr);
    sys.kmalloc       = (void* (*)(unsigned long, unsigned int))(unsigned long)kva(config.kmalloc_addr);
    sys.kfree         = (void  (*)(const void*))(unsigned long)kva(config.kfree_addr);
    sys.vmalloc       = (void* (*)(unsigned long))(unsigned long)kva(config.vmalloc_addr);
    sys.vfree         = (void  (*)(const void*))(unsigned long)kva(config.vfree_addr);
    sys.memset_impl   = (void* (*)(void*, int, unsigned long))(unsigned long)kva(config.memset_addr);
    sys.memcpy_impl   = (void* (*)(void*, const void*, unsigned long))(unsigned long)kva(config.memcpy_addr);
    sys.printk        = (int   (*)(const char*, ...))(unsigned long)kva(config.printk_addr);
    sys.syscall_table = (void*)(unsigned long)kva(config.syscall_table_addr);
    sys.init_task     = (void*)(unsigned long)kva(config.init_task_addr);
    sys.cred_offset   = config.cred_offset;
    sys.mm_struct_offset = 0;
    sys.task_in_thread_info_offset = offsetof(thread_info, task);
    sys.seccomp_offset = config.seccomp_offset;
    sys.thread_size   = THREAD_SIZE;
    sys.tif_seccomp_bit = 11;
    sys.sp_el0_is_current      = config.sp_el0_is_current;
    sys.sp_el0_is_thread_info  = config.sp_el0_is_thread_info;
    sys.thread_info_in_task    = config.thread_info_in_task;
    sys.has_syscall_wrapper    = config.has_syscall_wrapper;
    sys.kver           = (const char*)(unsigned long)kva((uint64_t)(unsigned long)config.kernel_version_str);
    sys.kpm_module_list_head = 0;
    sys.filp_open_fn   = (void* (*)(const char*, int, unsigned short))(unsigned long)kva(config.filp_open_addr);
    sys.kernel_read_fn = (long  (*)(void*, void*, unsigned long, unsigned long long*))(unsigned long)kva(config.kernel_read_addr);
    sys.filp_close_fn  = (int   (*)(void*, void*))(unsigned long)kva(config.filp_close_addr);
    sys.copy_from_user_fn = (unsigned long (*)(void*, const void*, unsigned long))(unsigned long)kva(config.copy_from_user_addr);
    sys.loader_base    = (void*)(unsigned long)kva(loader_bin_addr);
    sys.loader_size    = KPM_LOADER_BIN_SIZE;
    sys.loader_entry_offset = KPM_LOADER_ENTRY_OFFSET;

    std::string str_bytes = bytes2hex((const unsigned char*)&sys, sizeof(sys));
    out.push_back({ str_bytes, table_addr });
}

KpmEmbedResult kpm_embed_loader(const KpmEmbedConfig& config,
                                const SymbolRegion& available_region) {
    KpmEmbedResult result;

    if (KPM_LOADER_BIN_SIZE == 0) {
        std::cout << "[ERROR] KPM loader binary is empty" << std::endl;
        return result;
    }

    if (available_region.size < KPM_TOTAL_NEEDED) {
        std::cout << "[ERROR] Not enough kernel space for KPM loader: need "
                  << KPM_TOTAL_NEEDED << ", have " << available_region.size << std::endl;
        return result;
    }

    /* Layout:
     *   base_addr + 0                        → handler wrapper
     *   next 4 KiB boundary after wrapper    → loader binary
     *   loader_bin_addr + KPM_LOADER_BIN_SIZE → system table (8-byte aligned)
     */
    size_t base_addr = available_region.offset;
    size_t loader_bin_addr = (base_addr + KPM_WRAPPER_ESTIMATE + (KPM_LOADER_ALIGN - 1)) & ~(KPM_LOADER_ALIGN - 1);
    size_t system_table_addr = (loader_bin_addr + KPM_LOADER_BIN_SIZE + 7) & ~7ULL;

    std::cout << "KPM loader embedding:" << std::endl;
    std::cout << "  handler:     0x" << std::hex << base_addr << std::endl;
    size_t loader_entry_addr = loader_bin_addr + KPM_LOADER_ENTRY_OFFSET;

    std::cout << "  loader:      0x" << loader_bin_addr
              << " (" << std::dec << KPM_LOADER_BIN_SIZE << " bytes)" << std::endl;
    std::cout << "  entry:       0x" << std::hex << loader_entry_addr
              << " (offset 0x" << KPM_LOADER_ENTRY_OFFSET << ")" << std::endl;
    std::cout << "  system tbl:  0x" << std::hex << system_table_addr
              << " (" << std::dec << sizeof(kpm_system_table) << " bytes)" << std::endl;

    /* Step 1: Generate handler wrapper at base_addr */
    /* Determine which register holds the filename in the execve variant being patched.
     * For modern kernels: do_execveat_common / __do_execve_file: filename in x1
     * For older kernels: do_execve: filename in x0
     * We default to x0 and adjust based on the config.
     */
    int filename_reg = config.execve_filename_reg;
    bool filename_is_direct = config.execve_filename_is_direct != 0;
    auto handler_patches = kpm_generate_handler_wrapper(
        filename_reg, filename_is_direct, base_addr, system_table_addr, loader_entry_addr);
    if (handler_patches.empty()) {
        std::cout << "[ERROR] Failed to generate KPM handler wrapper" << std::endl;
        return result;
    }
    for (const auto& p : handler_patches) {
        size_t patch_size = p.str_bytes.length() / 2;
        if (p.write_addr < base_addr || p.write_addr > loader_bin_addr || patch_size > loader_bin_addr - p.write_addr) {
            std::cout << "[ERROR] KPM handler wrapper overlaps loader" << std::endl;
            return result;
        }
    }
    if (system_table_addr < available_region.offset ||
        system_table_addr - available_region.offset > available_region.size ||
        sizeof(kpm_system_table) > available_region.size - (system_table_addr - available_region.offset)) {
        std::cout << "[ERROR] KPM layout exceeds selected code cave" << std::endl;
        return result;
    }
    for (auto& p : handler_patches) result.patches.push_back(p);

    /* Step 2: Embed the KPM loader binary */
    {
        std::string str_bytes = bytes2hex(kpm_loader_bin, KPM_LOADER_BIN_SIZE);
        result.patches.push_back({ str_bytes, loader_bin_addr });
    }

    /* Step 3: Embed the system table */
    embed_system_table_bytes(config, result.patches, system_table_addr, loader_bin_addr);

    result.success = true;
    result.loader_start_addr = base_addr;
    result.loader_end_addr = system_table_addr + sizeof(kpm_system_table);
    result.system_table_addr = system_table_addr;
    result.command_handler_addr = base_addr;

    return result;
}
