#include "kpm_embed.h"
#include "analyze/base_func.h"
#include "patch_base.h"
#include "3rdparty/aarch64_asm_helper.h"

/* Generated by kpm/Makefile */
#include "kpm/kpm_loader_data.h"
#include "kpm/kpm_loader_layout.h"

using namespace asmjit;
using namespace asmjit::a64;

/* Forward declaration from kpm_command.cpp */
extern std::vector<patch_bytes_data> kpm_generate_handler_wrapper(
    int filename_reg, size_t handler_addr,
    size_t system_table_addr, size_t loader_entry_addr);

/* Total size needed in kernel memory:
 *   handler_wrapper (~256 bytes)
 * + KPM loader binary (KPM_LOADER_BIN_SIZE)
 * + KpmSystemTable (sizeof(kpm_system_table) + alignment)
 */
#define KPM_WRAPPER_ESTIMATE  512
#define KPM_TOTAL_NEEDED  (KPM_WRAPPER_ESTIMATE + KPM_LOADER_BIN_SIZE + sizeof(kpm_system_table) + 64)

static void embed_system_table_bytes(const KpmEmbedConfig& config,
                                     std::vector<patch_bytes_data>& out,
                                     size_t table_addr) {
    kpm_system_table sys;
    memset(&sys, 0, sizeof(sys));

    sys.kallsyms_lookup_name = (void* (*)(const char*))(unsigned long)config.kallsyms_lookup_name_addr;
    sys.kmalloc       = (void* (*)(unsigned long, unsigned int))(unsigned long)config.kmalloc_addr;
    sys.kfree         = (void  (*)(const void*))(unsigned long)config.kfree_addr;
    sys.vmalloc       = (void* (*)(unsigned long))(unsigned long)config.vmalloc_addr;
    sys.vfree         = (void  (*)(const void*))(unsigned long)config.vfree_addr;
    sys.memset_impl   = (void* (*)(void*, int, unsigned long))(unsigned long)config.memset_addr;
    sys.memcpy_impl   = (void* (*)(void*, const void*, unsigned long))(unsigned long)config.memcpy_addr;
    sys.printk        = (int   (*)(const char*, ...))(unsigned long)config.printk_addr;
    sys.syscall_table = (void*)(unsigned long)config.syscall_table_addr;
    sys.init_task     = (void*)(unsigned long)config.init_task_addr;
    sys.cred_offset   = config.cred_offset;
    sys.mm_struct_offset = 0;
    sys.task_in_thread_info_offset = offsetof(thread_info, task);
    sys.seccomp_offset = config.seccomp_offset;
    sys.thread_size   = THREAD_SIZE;
    sys.tif_seccomp_bit = 11;
    sys.sp_el0_is_current      = config.sp_el0_is_current;
    sys.sp_el0_is_thread_info  = config.sp_el0_is_thread_info;
    sys.thread_info_in_task    = config.thread_info_in_task;
    sys.has_syscall_wrapper    = config.has_syscall_wrapper;
    sys.kver           = config.kernel_version_str;
    sys.kpm_module_list_head = 0;
    sys.filp_open_fn   = (void* (*)(const char*, int, unsigned short))(unsigned long)config.filp_open_addr;
    sys.kernel_read_fn = (long  (*)(void*, void*, unsigned long, unsigned long long*))(unsigned long)config.kernel_read_addr;
    sys.filp_close_fn  = (int   (*)(void*, void*))(unsigned long)config.filp_close_addr;
    sys.loader_base    = (void*)0;  /* filled at runtime */
    sys.loader_size    = KPM_LOADER_BIN_SIZE;

    std::string str_bytes = bytes2hex((const unsigned char*)&sys, sizeof(sys));
    out.push_back({ str_bytes, table_addr });
}

KpmEmbedResult kpm_embed_loader(const KpmEmbedConfig& config,
                                const SymbolRegion& available_region) {
    KpmEmbedResult result;

    if (KPM_LOADER_BIN_SIZE == 0) {
        std::cout << "[ERROR] KPM loader binary is empty" << std::endl;
        return result;
    }

    if (available_region.size < KPM_TOTAL_NEEDED) {
        std::cout << "[ERROR] Not enough kernel space for KPM loader: need "
                  << KPM_TOTAL_NEEDED << ", have " << available_region.size << std::endl;
        return result;
    }

    /* Layout:
     *   base_addr + 0                        → handler wrapper
     *   base_addr + KPM_WRAPPER_ESTIMATE     → loader binary (aligned)
     *   loader_bin_addr + KPM_LOADER_BIN_SIZE → system table (8-byte aligned)
     */
    size_t base_addr = available_region.offset;
    size_t loader_bin_addr = (base_addr + KPM_WRAPPER_ESTIMATE + 7) & ~7ULL;
    size_t system_table_addr = (loader_bin_addr + KPM_LOADER_BIN_SIZE + 7) & ~7ULL;

    std::cout << "KPM loader embedding:" << std::endl;
    std::cout << "  handler:     0x" << std::hex << base_addr << std::endl;
    std::cout << "  loader:      0x" << loader_bin_addr
              << " (" << std::dec << KPM_LOADER_BIN_SIZE << " bytes)" << std::endl;
    std::cout << "  system tbl:  0x" << std::hex << system_table_addr
              << " (" << std::dec << sizeof(kpm_system_table) << " bytes)" << std::endl;

    /* Step 1: Generate handler wrapper at base_addr */
    /* Determine which register holds the filename in the execve variant being patched.
     * For modern kernels: do_execveat_common / __do_execve_file: filename in x1
     * For older kernels: do_execve: filename in x0
     * We default to x0 and adjust based on the config.
     */
    int filename_reg = 0; /* x0 — most common */
    auto handler_patches = kpm_generate_handler_wrapper(
        filename_reg, base_addr, system_table_addr, loader_bin_addr);
    if (handler_patches.empty()) {
        std::cout << "[ERROR] Failed to generate KPM handler wrapper" << std::endl;
        return result;
    }
    for (auto& p : handler_patches) result.patches.push_back(p);

    /* Step 2: Embed the KPM loader binary */
    {
        std::string str_bytes = bytes2hex(kpm_loader_bin, KPM_LOADER_BIN_SIZE);
        result.patches.push_back({ str_bytes, loader_bin_addr });
    }

    /* Step 3: Embed the system table */
    embed_system_table_bytes(config, result.patches, system_table_addr);

    result.success = true;
    result.loader_start_addr = base_addr;
    result.loader_end_addr = system_table_addr + sizeof(kpm_system_table);
    result.system_table_addr = system_table_addr;
    result.command_handler_addr = base_addr;

    return result;
}
